# Generated by Django 5.2 on 2025-04-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
    ]
